### ISSUE TITLE
Doesn't work on Chrome/Thorium

### ISSUE THREAD

**Issue by Rosentti** [MagicJinn/Block-Sponsor-Comments#18]
Recently switched to Thorium, since it's the only browser that has working x265 decoding.
On [this](https://www.youtube.com/watch?v=ZMGEO4URQqQ) video, nothing is being blocked:
![image](https://github.com/user-attachments/assets/d3b9ea94-453e-41b6-bc03-a26356d2f6e3)
![image](https://github.com/user-attachments/assets/c3c8414e-f8c5-4819-bea4-580ae745b88e)
This checkbox also doesn't save it's state:
![image](https://github.com/user-attachments/assets/2dffc939-b85b-4870-93b3-ca181e12691f)
Other videos also have this problem:
![image](https://github.com/user-attachments/assets/9515ece7-a826-43db-a26d-9c95927330b8)

I've copied the selector of a bit of ad text inside the description, in case it's useful:
`#description-inline-expander > yt-attributed-string > span > span:nth-child(1)`

**Comment by MagicJinn** [comment]
Turns out I am the dumbest guy. I did not add `"permissions":["storage"]` to the manifest v3 file, only to v2. The reason I did not find this during testing is because I use the manifest v2 during testing, even on Chrome. Thanks for the report, it should now be fixed!
Be aware that according to #9, some sponsors are no longer removed entirely (in the example of the video, it shortens it to `Ad: Remove your personal information from the web at `, which isn't ideal. I'm working on it.
