### ISSUE TITLE
[Firefox] 'Submit issue with current watchpage' detecting wrong video and URL

### ISSUE THREAD

**Issue by moosetwin0** [MagicJinn/Block-Sponsor-Comments#21]
here is a video of the issue:

https://github.com/user-attachments/assets/d437289c-4275-497f-a1d2-cf3af11ab97f

**Comment by moosetwin0** [comment]
This is with the latest version uploaded to the Firefox Add-Ons Browser (I have just installed it)

**Comment by MagicJinn** [comment]
Ah, I thought this issue wouldn't come up organically, but I was wrong. Thanks for reporting.

The reason this issue is happening is because the extension saves the title and URL when loading every *new* page, instead of getting the currently open one. This is a workaround to avoid asking for the "Tabs" permission.

Should be fixable, but until then, reloading the current page is a workaround.
